# https://taskfile.dev

version: "3"
silent: true

tasks:
  default:
    cmds:
      - DEBUG=true go run . {{.CLI_ARGS}}
    interactive: true
    desc: Run

  debug:
    cmds:
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - DEBUG=true LOG_LEVEL={{.LOG_LEVEL}} go run . {{.CLI_ARGS}}
    interactive: true
    desc: Run in debug mode. Run `task logs` to watch the logs.

  install:
    cmds:
      - go build -buildvcs=false . && go install -buildvcs=false .
    desc: Install with go

  diff:
    cmds:
      - task: install
      - GH_PAGER=diffnav gh pr diff {{.CLI_ARGS}}
    desc: "Run in gh pr diff. Usage: task diff -- <GitHub PR URL>"

  debug:info:
    cmds:
      - task: debug
        vars:
          LOG_LEVEL: info
    interactive: true
    desc: Run in debug mode with INFO level logs. Run `task logs` to watch the logs.

  dlv:
    cmds:
      - dlv debug --headless --api-version=2 --listen=127.0.0.1:43000 . -- {{.CLI_ARGS}}
    desc: Debug with dlv

  local-gh:
    cmds:
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - GH_PATH=/usr/local/bin/gh DEBUG=true go run ./main.go {{.CLI_ARGS}}
    interactive: true
    desc: Run in debug mode with a local gh install. Run `task logs` to watch the logs.

  logs:
    cmds:
      - rm -f ./debug.log
      - touch ./debug.log
      - tail -f ./debug.log
    interactive: true
    desc: Tail the debug logs

  lint:
    desc: Run base linters
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m
    env:
      GOEXPERIMENT: null

  lint-fix:
    desc: Run base linters and fix issues
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --fix
    env:
      GOEXPERIMENT: null

  test:
    cmds:
      - go test -v ./...
    desc: Run tests

  fmt:
    desc: Run gofumpt
    cmds:
      - gofumpt -w $(git ls-files '*.go')

  check-nerd-font:
    cmds:
      - nerdfix check $(fd --extension go)
    desc: Find broken nerdfont characters

  fix-nerd-font:
    cmds:
      - nerdfix fix --format=json $(fd --extension go)
    desc: Fix broken nerdfont icons

  release:
    cmds:
      - git checkout main
      - git tag $(svu next)
      - git push --tags
